import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// import { Provider } from "react-redux";
// import { store } from "./redux/store";
import ClientProvider from "./components/clientProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <GoogleOAuthProvider clientId="425719069655-aneq6sckal1sd764ousabd2v3o0k40oh.apps.googleusercontent.com">
        <html lang="en">
          <body className={inter.className}>
            <ClientProvider>{children}</ClientProvider>
          </body>
        </html>
      </GoogleOAuthProvider>
  );
}
